# _config.yml

# title: My Title (from config.yml file)
# Site settings
title: Terry's Sample Website
# theme: minima
theme: jekyll-theme-minimal
# description: Objective: Demonstrate how to use GitHub Pages
# url: "https://terryg99.github.io" # Update with your GitHub Pages URL
# baseurl: "" # Should be empty for GitHub Pages, or the name of subfolder if the site is served in a subfolder

# GitHub Pages settings
# repository: terryg99/SampleWebsite # Update with your GitHub repository
# branch: main # Update with your repository's main branch

